# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Your awesome title
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://foodlyweds.com" # the base hostname & protocol for your site
twitter_username: jekyllrb
github_username:  jordiesaenz

# Gems
gems: [github-pages, octopress, octopress-paginate, octopress-hooks, octopress-autoprefixer, font-awesome-sass]

# Collections
collections:
  posts:
    name: posts
    output: true
    path: /blog/posts/:path
  lists:
    name: lists
    output: true
    path: /lists/:path

# Pagination
pagination:
  limit: false
  per_page: 6
  permalink: /:num/
  title_suffix: " (page :num)"

paginate_path: "/blog/:num"

# Outputting
permalink:     /blog/posts/:slug


# Build settings
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
