# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Foodlyweds
email: hello@foodlyweds.com
description: We're two newlyweds living in Orange County, and to put it simply, we're eating all the things. Donuts. Coffee. Burgers. Boba. Pizza. You name it, we're into it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.foodlyweds.com" # the base hostname & protocol for your site
github_username:  jordiesaenz

# Gems
gems: [jekyll-paginate, octopress, octopress-paginate, octopress-hooks, octopress-autoprefixer, font-awesome-sass]

# Collections
collections:
  posts:
    name: posts
    output: true
    path: /blog/posts/:path
  lists:
    name: lists
    output: true
    path: /lists/:path

# Defaults
defaults:
  -
    scope:
      path: ""
    values:
      layout: "default"
  -
    scope:
      type: "posts"
    values:
      layout: "post"
  -
    scope:
      type: "lists"
    values:
      layout: "list"

# Pagination
pagination:
  limit: false
  per_page: 6

# Outputting
permalink:     /blog/posts/:slug


# Build settings
markdown: kramdown

# Sass
sass:
  sass_dir: _sass

# Exclude
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']
